version: 2.1

executors:
  build_ios_executor:
    macos:
      xcode: '11.5.0'

commands:
  install_ruby_gems:
    steps:
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }} # used if checksum fails
      - run:
          name: Set ruby version
          command: echo "ruby-2.6.3" > ~/.ruby-version
      - run:
          name: Install bundler
          command: sudo gem install bundler:2.1.4
      - run:
          name: Run bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  install_flutter_sdk:
    steps:
      - run:
          name: download flutter SDK
          command: git clone -b v1.15.3 https://github.com/flutter/flutter.git flutter
      - run:
          name: export flutter path
          command: |
            pwd
            echo 'export PATH="$PATH:`pwd`/flutter/bin"' >> $BASH_ENV
            source $BASH_ENV
  setup_flutter:
    steps:
      - run:
          name: Get packages flutter
          command: flutter pub get
      - run:
          name: Get cache
          command: flutter precache --no-android
      - run:
          name: Pod install
          command: pod install
          working_directory: ios
  fastlane_ios:
    steps:
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          working_directory: ios
  fastlane_android:
    steps:
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          working_directory: android
  install_gnu_sed:
    steps:
      - run:
          name: gnu-sed
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install gnu-sed
  install_lcov:
    steps:
      - run:
          name: install lcov
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
  run_test_coverage:
    steps:
      - run:
          name: Run test
          command: flutter test --coverage
          when: always
      - run:
          name: Run genhtml lcov
          when: always
          command: genhtml coverage/lcov.info -o coverage/html
      - store_artifacts:
          path: ./coverage

references:
  env_var_ios: &env_var_ios
    run:
      name: Add Environment variable ios
      command: |
        set -xe
        ls -la
        ./ops/env_var_ios.sh
  env_var_android: &env_var_android
    run:
      name: Add Environment variable android
      command: |
        set -xe
        ls -la
        ./ops/env_var_android.sh
  workspace_gcp_envs: &workspace_gcp_envs
    attach_workspace:
      at: ./

jobs:
  run_test:
    docker:
      - image: cirrusci/flutter:v1.15.3
    steps:
      - checkout
      - install_ruby_gems
      - run_test_coverage
  build_ios_dev:
    executor:
      name: build_ios_executor
    environment:
      FASTLANE_LANE: dev
    steps:
      - checkout
      - install_ruby_gems
      - install_flutter_sdk
      - install_gnu_sed
      - install_lcov
      - <<: *workspace_gcp_envs
      - <<: *env_var_ios
      - setup_flutter
      - run_test_coverage
      - fastlane_ios
  build_ios_fe:
    executor:
      name: build_ios_executor
    environment:
      FASTLANE_LANE: stg_fe
    steps:
      - checkout
      - install_ruby_gems
      - install_flutter_sdk
      - install_gnu_sed
      - install_lcov
      - <<: *workspace_gcp_envs
      - <<: *env_var_ios
      - setup_flutter
      - run_test_coverage
      - fastlane_ios
  build_ios_su:
    executor:
      name: build_ios_executor
    environment:
      FASTLANE_LANE: prod
    steps:
      - checkout
      - install_ruby_gems
      - install_flutter_sdk
      - install_gnu_sed
      - install_lcov
      - <<: *workspace_gcp_envs
      - <<: *env_var_ios
      - setup_flutter
      - run_test_coverage
      - fastlane_ios
  build_android_dev:
    docker:
      - image: cirrusci/flutter:v1.15.3
    environment:
      FASTLANE_LANE: dev
    steps:
      - checkout
      - install_ruby_gems
      - <<: *workspace_gcp_envs
      - <<: *env_var_android
      - run_test_coverage
      - run:
          name: flutter build
          command: flutter build appbundle --flavor development --release --target lib/main_development.dart
      - fastlane_android

workflows:
  test:
    jobs:
      - run_test
  build_app:
    jobs:
      - build_ios_dev:
          filters:
            branches:
              only:
                - circleci-project-setup
            # tags:
            #   only: /^dev.*/
            # branches:
            #   ignore: /.*/
      - build_ios_fe:
          filters:
            branches:
              only:
                - circleci-project-setup
            # tags:
            #   only: /^dev.*/
            # branches:
            #   ignore: /.*/
      - build_ios_su:
          filters:
            branches:
              only:
                - circleci-project-setup
            # tags:
            #   only: /^dev.*/
            # branches:
            #   ignore: /.*/
      - build_android_dev:
          filters:
            branches:
              only:
                - circleci-project-setup
